In [18]:
import pandas as pd
import numpy as nm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import Lasso,Ridge,ElasticNet,LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/cars.csv')
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

# **EDA**

In [3]:
df.describe()

,symboling,width,height,engine-size,city-mpg,highway-mpg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,65.907805,53.724878,126.907317,25.219512,30.751220,13227.478049
std,1.245307,2.145204,2.443522,41.642693,6.542142,6.886443,7902.651615
min,-2.000000,60.300000,47.800000,61.000000,13.000000,16.000000,5118.000000
25%,0.000000,64.100000,52.000000,97.000000,19.000000,25.000000,7788.000000
50%,1.000000,65.500000,54.100000,120.000000,24.000000,30.000000,10345.000000
75%,2.000000,66.900000,55.500000,141.000000,30.000000,34.000000,16500.000000
max,3.000000,72.300000,59.800000,326.000000,49.000000,54.000000,45400.000000

In [5]:
df.dtypes #normalized-losses and horsepower column are integer nut its data type is integer so check whats the problem

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower            object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [6]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [7]:
df["normalized-losses"].value_counts() #this ? are the problem replace with nan

?      41
161    11
91      8
150     7
134     6
128     6
104     6
85      5
94      5
65      5
102     5
74      5
168     5
103     5
95      5
106     4
93      4
118     4
148     4
122     4
83      3
125     3
154     3
115     3
137     3
101     3
119     2
87      2
89      2
192     2
197     2
158     2
81      2
188     2
194     2
153     2
129     2
108     2
110     2
164     2
145     2
113     2
256     1
107     1
90      1
231     1
142     1
121     1
78      1
98      1
186     1
77      1
Name: normalized-losses, dtype: int64

In [9]:
df["horsepower"].value_counts()

68     19
70     11
69     10
116     9
110     8
95      7
88      6
62      6
101     6
160     6
114     6
84      5
97      5
102     5
145     5
82      5
76      5
111     4
92      4
123     4
86      4
90      3
73      3
85      3
207     3
182     3
121     3
152     3
112     2
56      2
161     2
156     2
94      2
52      2
?       2
162     2
155     2
184     2
100     2
176     2
55      1
262     1
134     1
115     1
140     1
48      1
58      1
60      1
78      1
135     1
200     1
64      1
120     1
72      1
154     1
288     1
143     1
142     1
175     1
106     1
Name: horsepower, dtype: int64

In [15]:
#replacing ? with nan
df.replace("?",nm.nan,inplace = True)

In [16]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [19]:
#filling missing value with median
si = SimpleImputer(strategy = "median")

In [20]:
df.iloc[:,[1,11]]

    normalized-losses horsepower
0                 NaN        111
1                 NaN        111
2                 NaN        154
3                 164        102
4                 164        115
..                ...        ...
200                95        114
201                95        160
202                95        134
203                95        106
204                95        114

[205 rows x 2 columns]

In [21]:
df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])

<ipython-input-21-7482350b3d09>:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])

In [22]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,115.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,13495
1,3,115.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,16500
2,1,115.0,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154.0,19,26,16500
3,2,164.0,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102.0,24,30,13950
4,2,164.0,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,23,28,16845
201,-1,95.0,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160.0,19,25,19045
202,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134.0,18,23,21485
203,-1,95.0,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106.0,26,27,22470
204,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,19,25,22625

In [24]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [26]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [32]:
df.select_dtypes(int)

     symboling  engine-size  city-mpg  highway-mpg  price
0            3          130        21           27  13495
1            3          130        21           27  16500
2            1          152        19           26  16500
3            2          109        24           30  13950
4            2          136        18           22  17450
..         ...          ...       ...          ...    ...
200         -1          141        23           28  16845
201         -1          141        19           25  19045
202         -1          173        18           23  21485
203         -1          145        26           27  22470
204         -1          141        19           25  22625

[205 rows x 5 columns]

In [34]:
cat_col = df.select_dtypes(object).columns
cat_col

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [37]:
#ordinal encoder
oe = OrdinalEncoder()
df[cat_col] = oe.fit_transform(df[cat_col])

In [38]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,115.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,13495
1,3,115.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,16500
2,1,115.0,0.0,1.0,2.0,2.0,0.0,65.5,52.4,5.0,152,154.0,19,26,16500
3,2,164.0,1.0,1.0,3.0,1.0,0.0,66.2,54.3,3.0,109,102.0,24,30,13950
4,2,164.0,1.0,1.0,3.0,0.0,0.0,66.4,54.3,3.0,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,23,28,16845
201,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.8,55.5,3.0,141,160.0,19,25,19045
202,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,5.0,173,134.0,18,23,21485
203,-1,95.0,21.0,0.0,3.0,2.0,0.0,68.9,55.5,3.0,145,106.0,26,27,22470
204,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,19,25,22625

In [41]:
df.dtypes

symboling              int64
normalized-losses    float64
make                 float64
fuel-type            float64
body-style           float64
drive-wheels         float64
engine-location      float64
width                float64
height               float64
engine-type          float64
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

# **Splitting the data**

In [42]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [46]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.30,random_state=1)

# **Simple Linear Regression**

In [47]:
le = LinearRegression()
le.fit(xtrain,ytrain)
ypred = le.predict(xtest)
le.score(xtrain,ytrain),le.score(xtest,ytest) #overfitted model

(0.8504229026078215, 0.796485478542952)

# **Lasso**

In [48]:
l1 = Lasso() #by default leaning rate alpha = 1
l1.fit(xtrain,ytrain)
ypred = l1.predict(xtest)
le.score(xtrain,ytrain),le.score(xtest,ytest) #overfitted model

(0.8504229026078215, 0.796485478542952)

# **Tunning in Lasso**

In [52]:
for i in range(100,200):
  l1 = Lasso(alpha = i)
  l1.fit(xtrain,ytrain)
  l1.predict(xtest)
  print(f"alpha : {i}, train : {l1.score(xtrain,ytrain)}, test : {l1.score(xtest,ytest)}")

alpha : 100, train : 0.8372483974026499, test : 0.8092040910955614
alpha : 101, train : 0.8369899229541407, test : 0.8092979610738258
alpha : 102, train : 0.8367288785613758, test : 0.8093910017461712
alpha : 103, train : 0.8364651676681871, test : 0.8094832684251526
alpha : 104, train : 0.8361989818307348, test : 0.8095746503624812
alpha : 105, train : 0.8359302253870345, test : 0.8096652035299016
alpha : 106, train : 0.8356588978359675, test : 0.8097549282309099
alpha : 107, train : 0.8353849991129144, test : 0.8098438245155563
alpha : 108, train : 0.8351084257059385, test : 0.809931945484127
alpha : 109, train : 0.8348293842179737, test : 0.8100191840285438
alpha : 110, train : 0.8345477714936769, test : 0.8101055942385992
alpha : 111, train : 0.8342635877040369, test : 0.8101911760417996
alpha : 112, train : 0.8339767222137543, test : 0.8102759813628972
alpha : 113, train : 0.8336873954613211, test : 0.8103599056262563
alpha : 114, train : 0.8333954973355284, test : 0.810443001666504
alpha : 115, train : 0.8331010276993127, test : 0.810525269547536
alpha : 116, train : 0.8328038691204882, test : 0.8106067595950118
alpha : 117, train : 0.8325042561318754, test : 0.8106873701557593
alpha : 118, train : 0.8322020717101931, test : 0.8107671525374287
alpha : 119, train : 0.831897315909265, test : 0.8108461067199922
alpha : 120, train : 0.8315898643306087, test : 0.8109242812985725
alpha : 121, train : 0.8312799660294592, test : 0.8110015778648529
alpha : 122, train : 0.8309674969080165, test : 0.8110780460553539
alpha : 123, train : 0.8306523257994233, test : 0.8111537336006447
alpha : 124, train : 0.8303347149155724, test : 0.8112285440004979
alpha : 125, train : 0.8300145320017066, test : 0.811302526508727
alpha : 126, train : 0.8296917792068185, test : 0.8113756803829957
alpha : 127, train : 0.829366316475423, test : 0.8114480518748994
alpha : 128, train : 0.8290384195488707, test : 0.8115195488665822
alpha : 129, train : 0.8287079533571843, test : 0.8115902170896445
alpha : 130, train : 0.8283747703082013, test : 0.8116601017520375
alpha : 131, train : 0.8280391586533506, test : 0.8117291135142941
alpha : 132, train : 0.8277009785176217, test : 0.8117972963383392
alpha : 133, train : 0.8273600743513216, test : 0.8118646943166663
alpha : 134, train : 0.827016751920332, test : 0.8119312197807059
alpha : 135, train : 0.8266708579462198, test : 0.8119969172586021
alpha : 136, train : 0.8263223897906081, test : 0.8120617874347753
alpha : 137, train : 0.8259711936341727, test : 0.8121258693292266
alpha : 138, train : 0.8256175865009793, test : 0.8121890813322454
alpha : 139, train : 0.8252612405575876, test : 0.8122515055400706
alpha : 140, train : 0.8249024913515863, test : 0.8123130602354285
alpha : 141, train : 0.8245411708666053, test : 0.8123737869230406
alpha : 142, train : 0.8241771102161816, test : 0.8124337227741055
alpha : 143, train : 0.8238106530253967, test : 0.8124927911020222
alpha : 144, train : 0.8234416172134693, test : 0.8125510330331999
alpha : 145, train : 0.8230698280784812, test : 0.8126084835163163
alpha : 146, train : 0.8226956503354529, test : 0.8126650681694726
alpha : 147, train : 0.8223189013367542, test : 0.8127208248289379
alpha : 148, train : 0.8219393940513868, test : 0.8127757876072301
alpha : 149, train : 0.8215575086176153, test : 0.8128298860919089
alpha : 150, train : 0.8211730520262539, test : 0.8128831566524963
alpha : 151, train : 0.8207858295570518, test : 0.8129356313528258
alpha : 152, train : 0.8203962392797491, test : 0.8129872435786123
alpha : 153, train : 0.8200038659827094, test : 0.8130380604531806
alpha : 154, train : 0.8196091274468162, test : 0.8130880167485961
alpha : 155, train : 0.8192116048584221, test : 0.8131371754207155
alpha : 156, train : 0.8188117256012322, test : 0.8131854746070425
alpha : 157, train : 0.8184092752900354, test : 0.8132329459427781
alpha : 158, train : 0.8180040340448276, test : 0.813279617108145
alpha : 159, train : 0.8175964432833531, test : 0.8133254313927005
alpha : 160, train : 0.8171860531186916, test : 0.8133704442145948
alpha : 161, train : 0.8167733221546685, test : 0.8134146014856176
alpha : 162, train : 0.816357783218174, test : 0.8134579558972019
alpha : 163, train : 0.8159399130313314, test : 0.813500456125974
alpha : 164, train : 0.8155192326252293, test : 0.8135421513909359
alpha : 165, train : 0.8150962240434021, test : 0.8135829946288721
alpha : 166, train : 0.8146706427093288, test : 0.8136230103114317
alpha : 167, train : 0.814242239042142, test : 0.8136622185802584
alpha : 168, train : 0.8138115184156173, test : 0.8137005774315418
alpha : 169, train : 0.8133779670184814, test : 0.813738127152358
alpha : 170, train : 0.812942107429732, test : 0.8137748292356427
alpha : 171, train : 0.8125034086683014, test : 0.8138107203716055
alpha : 172, train : 0.8120624104546714, test : 0.8138457657584284
alpha : 173, train : 0.8116185647484577, test : 0.8138799982828286
alpha : 174, train : 0.8111721398138243, test : 0.8139134011642214
alpha : 175, train : 0.8107234361496893, test : 0.8139459609474125
alpha : 176, train : 0.8102718648859881, test : 0.8139777051490644
alpha : 177, train : 0.8098180239059947, test : 0.8140086084473978
alpha : 178, train : 0.8093613132661216, test : 0.814038693771297
alpha : 179, train : 0.808902341338292, test : 0.8140679405535107
alpha : 180, train : 0.8084404898252787, test : 0.814096367226358
alpha : 181, train : 0.8079760625391161, test : 0.8141239640881857
alpha : 182, train : 0.8075093897331423, test : 0.8141507260035142
alpha : 183, train : 0.8070398161300381, test : 0.814176664435304
alpha : 184, train : 0.8065680080542684, test : 0.8142017704223898
alpha : 185, train : 0.8060932933491103, test : 0.8142260504255305
alpha : 186, train : 0.8056160025244101, test : 0.8142495005999419
alpha : 187, train : 0.8051364964854257, test : 0.814272122341565
alpha : 188, train : 0.8046540668179516, test : 0.8142939142513763
alpha : 189, train : 0.8041690622414064, test : 0.8143148763571931
alpha : 190, train : 0.8036814832401014, test : 0.8143350086553349
alpha : 191, train : 0.8031917275605561, test : 0.8143543185997575
alpha : 192, train : 0.802699025870538, test : 0.8143727932940247
alpha : 193, train : 0.8022037529436447, test : 0.8143904384269913
alpha : 194, train : 0.801705909538015, test : 0.8144072540570484
alpha : 195, train : 0.8012054966196824, test : 0.8144232402636585
alpha : 196, train : 0.800702515179387, test : 0.8144383971441083
alpha : 197, train : 0.8001973998845261, test : 0.8144527419474971
alpha : 198, train : 0.799689294783284, test : 0.8144662423958203
alpha : 199, train : 0.7991786241960611, test : 0.8144789139191477

In [53]:
#at alpha = 175 we get both the accuracy similer

# **Final Model**

In [54]:
le = Lasso(alpha = 175)
le.fit(xtrain,ytrain)
ypred = le.predict(xtest)
le.score(xtrain,ytrain),le.score(xtest,ytest)

(0.8107234361496893, 0.8139459609474125)

# **Ridge**

In [55]:
l2 = Ridge()
l2.fit(xtrain,ytrain)
ypred = l2.predict(xtest)
l2.score(xtrain,ytrain),l2.score(xtest,ytest) #overfitted model

(0.8435840853399227, 0.8075632224690537)

# **Hyperparameter in Ridge**

In [57]:
for i in range(1,50):
  l2 = Ridge(alpha = i)
  l2.fit(xtrain,ytrain)
  ypred = l2.predict(xtest)
  print(f"alpha : {i}, train : {l2.score(xtrain,ytrain)}, test : {l2.score(xtest,ytest)}")

alpha : 1, train : 0.8435840853399227, test : 0.8075632224690537
alpha : 2, train : 0.8356695734845093, test : 0.8112192014374252
alpha : 3, train : 0.8296379623431074, test : 0.8129299663310143
alpha : 4, train : 0.8250699092246865, test : 0.8138839096972439
alpha : 5, train : 0.8215093087765017, test : 0.8144682684596016
alpha : 6, train : 0.818648610383485, test : 0.814843562726523
alpha : 7, train : 0.8162882573020809, test : 0.8150880725612082
alpha : 8, train : 0.8142964263180522, test : 0.8152447305071578
alpha : 9, train : 0.8125835227290971, test : 0.8153392574436444
alpha : 10, train : 0.8110868722186454, test : 0.8153881483263246
alpha : 11, train : 0.8097614513602518, test : 0.8154025610279505
alpha : 12, train : 0.8085741366835053, test : 0.8153903693701572
alpha : 13, train : 0.8075000372738094, test : 0.8153573212892009
alpha : 14, train : 0.8065200924084592, test : 0.815307729407223
alpha : 15, train : 0.8056194580416447, test : 0.8152449025615434
alpha : 16, train : 0.804786398073303, test : 0.815171426484327
alpha : 17, train : 0.8040115065187472, test : 0.815089352768959
alpha : 18, train : 0.8032871514648678, test : 0.8150003299437463
alpha : 19, train : 0.8026070707304608, test : 0.8149056967781803
alpha : 20, train : 0.8019660732378706, test : 0.8148065502246251
alpha : 21, train : 0.8013598153077787, test : 0.8147037958811014
alpha : 22, train : 0.8007846308878105, test : 0.8145981861304741
alpha : 23, train : 0.8002374011637663, test : 0.8144903494117507
alpha : 24, train : 0.7997154533085167, test : 0.8143808129927236
alpha : 25, train : 0.7992164810518412, test : 0.8142700209017133
alpha : 26, train : 0.798738481776389, test : 0.814158348199973
alpha : 27, train : 0.7982797062609372, test : 0.8140461124511116
alpha : 28, train : 0.7978386181969568, test : 0.8139335830177277
alpha : 29, train : 0.7974138613263305, test : 0.813820988655486
alpha : 30, train : 0.7970042325726077, test : 0.8137085237599927
alpha : 31, train : 0.7966086599233979, test : 0.8135963535381273
alpha : 32, train : 0.7962261841073035, test : 0.8134846183137231
alpha : 33, train : 0.795855943322788, test : 0.8133734371313502
alpha : 34, train : 0.7954971604380747, test : 0.8132629107871043
alpha : 35, train : 0.7951491322043275, test : 0.813153124388708
alpha : 36, train : 0.7948112201189456, test : 0.8130441495267421
alpha : 37, train : 0.7944828426489627, test : 0.8129360461229017
alpha : 38, train : 0.7941634685815295, test : 0.8128288640086807
alpha : 39, train : 0.7938526113131447, test : 0.8127226442780505
alpha : 40, train : 0.7935498239245845, test : 0.8126174204498453
alpha : 41, train : 0.7932546949164723, test : 0.8125132194693003
alpha : 42, train : 0.7929668445028011, test : 0.8124100625731352
alpha : 43, train : 0.7926859213776736, test : 0.8123079660384829
alpha : 44, train : 0.7924115998850197, test : 0.8122069418326152
alpha : 45, train : 0.7921435775328082, test : 0.8121069981777135
alpha : 46, train : 0.7918815728028477, test : 0.8120081400426531
alpha : 47, train : 0.7916253232151242, test : 0.811910369571946
alpha : 48, train : 0.7913745836120685, test : 0.811813686460422
alpha : 49, train : 0.7911291246334808, test : 0.8117180882809594

In [58]:
#at alpha = 7 we get both the accuracy similar

# **Final Model**

In [59]:
l2 = Ridge(alpha = 7)
l2.fit(xtrain,ytrain)
ypred = l2.predict(xtest)
l2.score(xtrain,ytrain),l2.score(xtest,ytest)

(0.8162882573020809, 0.8150880725612082)

# **3.ElasticNet**

In [61]:
en = ElasticNet(alpha = 1)
en.fit(xtrain,ytrain)
ypred = en.predict(xtest)
en.score(xtrain,ytrain),en.score(xtest,ytest) #generalized model

(0.7866253599240464, 0.8098264817256129)

# Tunning

In [64]:
for i in range(1,10):
  en = ElasticNet(alpha = i)
  en.fit(xtrain,ytrain)
  ypred = en.predict(xtest)
  print(f"alpha : {i}, train : {en.score(xtrain,ytrain)}, test : {en.score(xtest,ytest)}")

alpha : 1, train : 0.7866253599240464, test : 0.8098264817256129
alpha : 2, train : 0.7785982256935363, test : 0.8060357239149383
alpha : 3, train : 0.7741098728697712, test : 0.8038330303232792
alpha : 4, train : 0.7710450291333583, test : 0.8023305288839748
alpha : 5, train : 0.7687371063143833, test : 0.8012075675535992
alpha : 6, train : 0.7668931957678061, test : 0.8003179782274955
alpha : 7, train : 0.765360462271702, test : 0.7995845026702189
alpha : 8, train : 0.7640627321201632, test : 0.7989624987950101
alpha : 9, train : 0.7629190144346729, test : 0.798423446790505